Feat/4 play song
DeveloperAcademy-POSTECH/CultureCenter-AppleMusicClone-CozyKyuRookie pull request #13
Opened 2022-07-08 12:10 UTC by cozytk

## 작업 내용

- [x] 노래 재생
- [x] 노래 일시정지

## 리뷰 받고 싶은 내용 ( 질문할 내용 )

- 현재 `SongRow` 파일에 `private func toggleSong` 으로 선언하였는데, MVVM 구조에 따라 viewModel에 넣어주어야 하는 것인지
- 추후에 밑에 상태바를 구현하기 위해서는 `SongManager` 같은 클래스로 만들어서 `static` 변수로 `shared` 형태로 전역으로 사용하도록 개선하는 것이 좋을지

## Screenshot

2022-07-08 12:44 UTC, cozytk commented
### ToDo
현재는 **미리듣기**로 구현이 되어있는데 향후 멤버십 구독 형태에 따라 풀노래도 들을 수 있도록 개선해야할 것 같습니다.
더 조사를 해봐야 알겠지만 멤버십 구독을 반영하려면 Apple Music API 가 아니라 MusicKit 을 써야 하는 것으로 보입니다

2022-07-08 12:58 UTC, cozytk commented on AppleMusicClone/Views/SearchViews/SongRow.swift
> +                Button {
@kyustudyo @Rookie0031 
다시 생각해보니 `Button` 이 아닌 `tabGesture` 로 구현하는게 맞았을까요?
둘이 차이가 있다면 무엇이 있을까여

2022-07-09 02:01 UTC, Rookie0031 requested changes
고생하셨습니다!

2022-07-09 02:01 UTC, Rookie0031 commented on AppleMusicClone/Views/SearchViews/SongRow.swift
> +    private func toggleSong(url: URL, willChangeSong: Bool) -> URL? {
## Suggest
 파라미터로 willChangeSong 이 있는데 처음 읽었을 때는 음악을 바꾸는 불리언 값인줄 알아서 이것도 바꾸는게 어떨까요?? 
혹시 toggleSong 말고 이름이 있을까요?? 이건 저도 잘 생각안나네요 ㅋㅋㅋㅋ
ex.
 private func toggleSong(url: URL, play: Bool)

2022-07-09 03:57 UTC, cozytk commented on AppleMusicClone/Views/SearchViews/SongRow.swift
> +    @State var audioPlayer: AVPlayer!
privated으로 선언하고 접근이 필요한 최상단에 value를 배치시키는 것!! 확인했습니다
자세한 이유는 저도 잘 모르겠지만 스레드에서의 충돌 방지같네요!!
적극 동의합니다! 아티클까지 첨부해주셔서 감사합니다

2022-07-09 04:00 UTC, cozytk commented on AppleMusicClone/Views/SearchViews/SongRow.swift
> +                Button {
<img width="805" alt="image" src="https://user-images.githubusercontent.com/59143479/178090739-2b4ebcfb-debe-4003-9b84-079e6166377d.png">
지금은 해당 cell 의 어떤 영역을 클릭해도 재생이 되는 구조라서 `Button` 으로 유지하고 향후 앨범사진을 눌렀을 시 앨범이 나오거나, 상세화면을 볼 수있는 더보기 같은 버튼을 만든다면 `onTapGesture`로 전환하겠습니다!

2022-07-09 04:01 UTC, cozytk commented on AppleMusicClone/Views/SearchViews/SongRow.swift
> +    private func toggleSong(url: URL, willChangeSong: Bool) -> URL? {
음악을 바꾸는 불리언 값 맞습니다!
같은 노래가 재생될때는 같은 노래만 토글되고 다른 노래를 재생하면 새로운 노래가 재생됩니다
`isNewSong` 같은 네이밍은 어떤가요?

2022-07-09 04:03 UTC, cozytk commented on AppleMusicClone/Views/SearchViews/SongRow.swift
> +    private func toggleSong(url: URL, willChangeSong: Bool) -> URL? {
`toggleSong`도 직관적이지 않군여.. 
`toggleSongState`
`onAndOffSong`
`onAndOffSongState`
정도가 생각나는 것 같습니다

2022-07-09 04:04 UTC, cozytk commented
@Rookie0031 리뷰확인했습니다
@kyustudyo kyu도 리뷰 부탁드릴게요~

2022-07-09 04:12 UTC, kyustudyo approved these changes
수고하셨습니다 노래 잘 나오네요~

2022-07-09 04:12 UTC, kyustudyo commented on AppleMusicClone/Views/SearchViews/SongRow.swift
> +    private func toggleSong(url: URL, willChangeSong: Bool) -> URL? {
isNewSong도 괜찮은 것 같습니다 ㅎ

2022-07-09 04:12 UTC, kyustudyo commented on AppleMusicClone/Views/SearchViews/SongRow.swift
> +    private func toggleSong(url: URL, willChangeSong: Bool) -> URL? {
혹시 return type이 optional로 하신 이유가 있으실까요?
```swift
guard let url = searchViewModel.songs[index].songUrl else { return }
```
에서 이미 url이 unwrap 되지 않을까요?

2022-07-09 04:15 UTC, cozytk commented on AppleMusicClone/Views/SearchViews/SongRow.swift
> +                Button {
@kyustudyo  눌렀다는 표시가 onTapGesture와 Button의 차이중 하나군여!

2022-07-09 06:00 UTC, kyustudyo commented
1. 현재 SongRow 파일에 private func toggleSong 으로 선언하였는데, MVVM 구조에 따라 viewModel에 넣어주어야 하는 것인지

2. 추후에 밑에 상태바를 구현하기 위해서는 SongManager 같은 클래스로 만들어서 static 변수로 shared 형태로 전역으로 사용하도록 개선하는 것이 좋을지

-> toggleSong 기능도 SongManger에 포함될 것 같습니다. 매니저 또는 viewModel이 있으면 좋을 것 같습니다. 싱글톤 또는 environmentObject 가 되지않을까요? 좀 더 알아보겠습니다.

2022-07-09 06:20 UTC, cozytk commented on AppleMusicClone/Views/SearchViews/SongRow.swift
> +    private func toggleSong(url: URL, willChangeSong: Bool) -> URL? {
@kyustudyo 맞네요 수정하겠습니다

2022-07-09 07:49 UTC, cozytk commented
@Rookie0031

> -> 잘 모르겟습니다. 규나 비비한테 물어봐야겠네요... 그런데 "shared 형태로 전역으로 사용한다" 는게 어떤 거인지 잘모르겠는데 예시가 있을까요??

`URLSession.shared` 같은 예시입니다!

@kyustudyo 
> -> toggleSong 기능도 SongManger에 포함될 것 같습니다. 매니저 또는 viewModel이 있으면 좋을 것 같습니다. 싱글톤 또는 environmentObject 가 되지않을까요? 좀 더 알아보겠습니다.

저도 싱글톤이나 `environmentObject`중에 고민해보겠습니다!

2022-07-09 10:03 UTC, cozytk commented on AppleMusicClone/Views/SearchViews/SongRow.swift
> +    @State var audioPlayer: AVPlayer!
[ec5b574](https://github.com/DeveloperAcademy-POSTECH/CultureCenter-AppleMusicClone-CozyKyuRookie/pull/13/commits/ec5b5743fabd525626616235d8240fe6520f1fc0) 반영완료!

2022-07-09 10:03 UTC, cozytk commented on AppleMusicClone/Views/SearchViews/SongRow.swift
> +    private func toggleSong(url: URL, willChangeSong: Bool) -> URL? {
[ec5b574](https://github.com/DeveloperAcademy-POSTECH/CultureCenter-AppleMusicClone-CozyKyuRookie/pull/13/commits/ec5b5743fabd525626616235d8240fe6520f1fc0) 반영완료!

2022-07-09 10:03 UTC, cozytk commented on AppleMusicClone/Views/SearchViews/SongRow.swift
> +    private func toggleSong(url: URL, willChangeSong: Bool) -> URL? {
[ec5b574](https://github.com/DeveloperAcademy-POSTECH/CultureCenter-AppleMusicClone-CozyKyuRookie/pull/13/commits/ec5b5743fabd525626616235d8240fe6520f1fc0) 반영완료!

2022-07-09 10:04 UTC, merged